% Script to do a quick run-through of the test points

% Required objects in memory:
% 1. robot = RX130('COM6');
% 2. model = geometricModel();
% 3. load('C:\Users\wberry\Documents\MATLAB\ROBOT_V1\extensions\Patrick\Calibration\goodJset.mat');
%   or similar set generated by testJs()/histResults combo.

%moveRobot(robot,model,model.Home);
currentPosition = robot.whereJ();
model.setJ(currentPosition);
jSet = goodJset(:,1:6);

for n = 1:size(jSet,1)
    % For big movements, return home first. Otherwise, try to go.
    currentPosition = robot.whereJ();
    if abs(currentPosition(1,1) - jSet(n,1)) > pi/2
        % Carefully adjust: Joint 2
        if currentPosition(2) < -pi/2 && n ~= 1
            backJ = robot.whereJ() + [0,0.6,0,0,0,0];
        elseif n ~= 1
            backJ = robot.whereJ() - [0,0.6,0,0,0,0];
        else
            backJ = robot.whereJ();
        end
        % Joint 5
        backJ(5) = model.Home(5);
        moveCarefully(robot,model,backJ);
        %robot.moveJ(model.Home);
        moveRobot(robot, model, model.Home);
        nextPosition = [jSet(n,1), model.Home(2:5), jSet(n,6)];
        %robot.moveJ(nextPosition);
        moveRobot(robot,model,nextPosition);
        [results(n,1:7) robotCrashed] = moveProtected(robot, model, jSet(n,:), @takeMeasurement);
        %[robotCrashed preCrashJ] = simulateRun(model, jSet(n,:));
    else
        [results(n,1:7) robotCrashed] = moveProtected(robot, model, jSet(n,:), @takeMeasurement);
        %[robotCrashed preCrashJ] = simulateRun(model, jSet(n,:));
    end
    
    % If we have finished a sphere cluster, back off a bit
    % Otherwise, just update the current position
    if ~robotCrashed && (goodJset(n,7) ~= goodJset(n+1,7) || goodJset(n,8) ~= goodJset(n+1,8))
       % Carefully move joint 2 up by 0.5
       if currentPosition(2) < -pi/2
            backJ = robot.whereJ() + [0,0.5,0,0,0,0];
       else
            backJ = robot.whereJ() - [0,0.5,0,0,0,0];
       end
       %[robotCrashed preCrashJ] = simulateRun(model, backJ);
       moveProtected(robot,model,backJ);
       currentPosition = robot.whereJ();
    elseif ~robotCrashed
        currentPosition = robot.whereJ();
    else
        crashCount = 1;
        while robotCrashed && crashCount < 3
            % A crash has occured! Back up and try again.
            fprintf('A model collision (%d) has ocurred. Returning to the previous position to try again\n',n);
            beep;
            
            % Move the second joint "up"
            currentPosition = robot.whereJ();
            if currentPosition(2) < -pi/2
                backJ = robot.whereJ() + [0,0.2,0,0,0,0];
            else
                backJ = robot.whereJ() - [0,0.2,0,0,0,0];
            end
%             % Move the fifth joint "straight"
%             if currentPosition(5) < 0
%                 backJ = backJ + [0,0,0,0,0.3,0];
%             else
%                 backJ = backJ - [0,0,0,0,0.3,0];
%             end
            model.setJ(robot.whereJ());
            %[robotCrashed preCrashJ] = simulateRun(model, backJ);
            [trash robotCrashed] = moveProtected(robot,model,backJ);
            currentPosition = robot.whereJ();
            %robot.moveJ([currentPosition(1:4), model.Home(5), currentPosition(6)]);
            %robot.moveJ([currentPosition(1:4),model.Home(5),jSet(n,6)]);
            if ~robotCrashed
                moveRobot(robot,model,[currentPosition(1:4), model.Home(5), currentPosition(6)]);
                moveRobot(robot,model,[currentPosition(1:4),model.Home(5),jSet(n,6)]);
            end
            %currentPosition = model.J;
            currentPosition = robot.whereJ();
            model.setJ(robot.whereJ());
            
            if robotCrashed
                fprintf('Crashed again, this is a problem. Try to skip it\n');
                results(n,:) = zeros(size(results,2));
                break;
            end
            
            % Try to make the correct movement again
            [results(n,1:7) robotCrashed] = moveProtected(robot, model, jSet(n,:), @takeMeasurement);
            if robotCrashed
                crashCount = crashCount + 1;
            else
                crashCount = 0;
            end
        end
    end
    
    % Add sphere number
    results(n,8) = goodJset(n,8);
    % Save every 5 data points
    if mod(n,5) == 0
        save('results.mat');
    end
    
    fprintf('Now finished data point %d. Reading: %d\n',n, results(n,1));
end